[package]
name = "test-mopa"
version = "0.1.0"
authors = ["Katsuki Kobayashi <rare@tirasweel.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mopa = "0.2.2"
rand = "0.7.3"
